apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-image-updater
    app.kubernetes.io/part-of: argocd
data:
  # Git configuration
  git.user: argocd-image-updater
  git.email: argocd-image-updater@noreply.github.com
  
  # Registry configuration
  registries.conf: |
    registries:
    - name: GitHub Container Registry
      prefix: ghcr.io
      api_url: https://ghcr.io
      credentials: secret:argocd/github-token#token
      default: true
      
  # Image updater configuration
  applications: |
    # Docker app staging
    docker-app-staging:
      image_list:
        - ghcr.io/mihuyen/ptuddn-assign/docker
      update_strategy: latest
      git_branch: develop
      write_back_method: git
      
    # Docker app production  
    docker-app-production:
      image_list:
        - ghcr.io/mihuyen/ptuddn-assign/docker
      update_strategy: semver
      git_branch: main
      write_back_method: git
      
    # K8s demo staging
    k8s-demo-staging:
      image_list:
        - ghcr.io/mihuyen/ptuddn-assign/k8s
      update_strategy: latest
      git_branch: develop
      write_back_method: git
      
    # K8s demo production
    k8s-demo-production:
      image_list:
        - ghcr.io/mihuyen/ptuddn-assign/k8s
      update_strategy: semver
      git_branch: main
      write_back_method: git

  # Log configuration
  log.level: info