version: 2
updates:
  # Maven dependencies for Docker module
  - package-ecosystem: "maven"
    directory: "/docker"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    commit-message:
      prefix: "deps(docker)"
      include: "scope"
    reviewers:
      - "@mihuyen"
    labels:
      - "dependencies"
      - "docker-module"
    open-pull-requests-limit: 5
    
  # Maven dependencies for SSO module
  - package-ecosystem: "maven"
    directory: "/sso"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    commit-message:
      prefix: "deps(sso)"
      include: "scope"
    reviewers:
      - "@mihuyen"
    labels:
      - "dependencies"
      - "sso-module"
    open-pull-requests-limit: 5
    
  # Maven dependencies for K8s module
  - package-ecosystem: "maven"
    directory: "/k8s"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    commit-message:
      prefix: "deps(k8s)"
      include: "scope"
    reviewers:
      - "@mihuyen"
    labels:
      - "dependencies"
      - "k8s-module"
    open-pull-requests-limit: 5
    
  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
    commit-message:
      prefix: "deps(docker-image)"
      include: "scope"
    reviewers:
      - "@mihuyen"
    labels:
      - "dependencies"
      - "docker-image"
    open-pull-requests-limit: 3
    
  - package-ecosystem: "docker"
    directory: "/k8s"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
    commit-message:
      prefix: "deps(k8s-docker)"
      include: "scope"
    reviewers:
      - "@mihuyen"
    labels:
      - "dependencies"
      - "docker-image"
    open-pull-requests-limit: 3
    
  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:00"
    commit-message:
      prefix: "deps(actions)"
      include: "scope"
    reviewers:
      - "@mihuyen"
    labels:
      - "dependencies"
      - "github-actions"
    open-pull-requests-limit: 5