name: Cleanup

on:
  schedule:
    # Run cleanup weekly on Sunday at 3 AM UTC
    - cron: '0 3 * * 0'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  cleanup-packages:
    name: Cleanup Old Container Images
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
      
    steps:
    - name: Delete old container images
      uses: actions/delete-package-versions@v4
      with:
        package-name: ${{ github.event.repository.name }}
        package-type: 'container'
        min-versions-to-keep: 10
        delete-only-untagged-versions: false
        
  cleanup-artifacts:
    name: Cleanup Old Artifacts
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      actions: write
      
    steps:
    - name: Delete old artifacts
      uses: geekyeggo/delete-artifact@v2
      with:
        name: |
          test-results
          jar-artifact
          dependency-check-report
          load-test-results
        failOnError: false
        useGlob: true
        
  cleanup-cache:
    name: Cleanup Old Cache
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      actions: write
      
    steps:
    - name: Cleanup old cache entries
      run: |
        # List all caches
        gh api \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/${{ github.repository }}/actions/caches \
          --jq '.actions_caches[] | select(.created_at < (now - 86400 * 7 | strftime("%Y-%m-%dT%H:%M:%SZ"))) | .id' \
        | while read cache_id; do
          echo "Deleting cache $cache_id"
          gh api \
            --method DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/actions/caches/$cache_id
        done
      env:
        GH_TOKEN: ${{ github.token }}
