name: Simple Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Say Hello
      run: echo "Hello World! CI is working!"
      
    - name: List files
      run: ls -la
      
    - name: Check Java files
      run: find . -name "*.java" | head -5