apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-demo-staging
  namespace: argocd
  labels:
    app: k8s-demo
    environment: staging
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  
  # Source configuration
  source:
    repoURL: https://github.com/mihuyen/PTUDDN-assign.git
    targetRevision: develop
    path: k8s/k8s
    
  # Destination configuration
  destination:
    server: https://kubernetes.default.svc
    namespace: k8s-demo-staging
    
  # Sync policy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
        
  # Health and sync configuration
  revisionHistoryLimit: 10
  
  # Ignore differences for certain fields
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
    - group: autoscaling
      kind: HorizontalPodAutoscaler
      jsonPointers:
        - /spec/minReplicas
        - /spec/maxReplicas
    - group: ""
      kind: Service
      jsonPointers:
        - /spec/clusterIP