apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-stack
  namespace: argocd
  labels:
    app: monitoring
    environment: shared
  annotations:
    argocd.argoproj.io/sync-wave: "0"  # Deploy monitoring first
spec:
  project: default
  
  # Source configuration
  source:
    repoURL: https://github.com/mihuyen/PTUDDN-assign.git
    targetRevision: main
    path: k8s/k8s
    directory:
      include: |
        prometheus-*.yaml
        grafana-*.yaml
    
  # Destination configuration
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
    
  # Sync policy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
        
  # Health and sync configuration
  revisionHistoryLimit: 5
  
  # Ignore differences for certain fields
  ignoreDifferences:
    - group: ""
      kind: ConfigMap
      jsonPointers:
        - /data  # Allow config updates without sync issues