apiVersion: v1
kind: Service
metadata:
  name: k8s-demo-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  type: LoadBalancer  # Use LoadBalancer for production