# Dependabot configuration for automatic dependency updates
version: 2

updates:
  # Enable version updates for Maven
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "@octocat"
    assignees:
      - "@octocat"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "java"
    ignore:
      # Ignore major version updates for Spring Boot
      - dependency-name: "org.springframework.boot:*"
        update-types: ["version-update:semver-major"]
      
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 3
    reviewers:
      - "@octocat"
    assignees:
      - "@octocat"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
      
  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 3
    reviewers:
      - "@octocat"
    assignees:
      - "@octocat"
    commit-message:
      prefix: "docker"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"